apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "instrument-id-agent.fullname" . }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.state.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
