apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instrument-id-agent.fullname" . }}
type: Opaque
stringData:
  instrument-id-api-key: {{ required "apiKey is required" .Values.apiKey | quote }}
